[project]
name = "shared"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["pathlib>=1.0.1", "torch>=2.8.0"]

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"
backend-path = ['src']
