[project]
name = "diffusion"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "diffusers>=0.34.0",
    "einops>=0.8.1",
    "matplotlib>=3.10.5",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[dependency-groups]
dev = ["ipykernel>=6.30.1", "ipython>=9.4.0", "pip>=25.2"]
